version: "3"

services:
  advanced_procws:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8004 --reload"
    image: advanced_proc:latest
    container_name: advanced_proc
    ports:
      - "8004:8004"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres_advanced_proc

  advanced_procws2:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8005 --reload"
    image: advanced_proc2:latest
    container_name: advanced_proc2
    ports:
      - "8005:8005"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres_advanced_proc

  postgres_advanced_proc:
    image: postgres:latest
    container_name: pg_advanced_proc
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "8003:8003"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' -c port=8003

  nginx:
    image: nginx:alpine
    container_name: advanced_proc_nginx
    ports:
      - "8069:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx

volumes:
  postgres_data:
